[package]
name = "simple-list"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sortable-js = { path = "../.." }
wasm-bindgen = "0.2.83"
web-sys = { version = "0.3.60", features = ["console", "Document", "Element", "Window"] }
